Traceback (most recent call last):
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\nbclient\client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import numpy as np
from statsmodels.tsa.arima_process import arma_acovf
from scipy.linalg import toeplitz

from matplotlib import rc
rc('font',**{'family':'serif','serif':['Palatino']})
rc('text', usetex=True)


plt.rcParams.update({'ytick.left' : True,
                     "xtick.bottom" : True,
                     "ytick.major.size": 0,
                     "ytick.major.width": 0,
                     "xtick.major.size": 0,
                     "xtick.major.width": 0,
                     "ytick.direction": 'in',
                     "xtick.direction": 'in',
                     'ytick.major.right': False,
                     'xtick.major.top': True,
                     'xtick.top': True,
                     'ytick.right': True,
                     'ytick.labelsize': 18,
                     'xtick.labelsize': 18
                    })

def correlation_from_covariance(covariance):
    v = np.sqrt(np.diag(covariance))
    outer_v = np.outer(v, v)
    correlation = covariance / outer_v
    correlation[covariance == 0] = 0
    return correlation

n_obs = 20
arparams = np.array([.80])
maparams = np.array([0])
ar = np.r_[1, -arparams] # add zero-lag and negate
ma = np.r_[1, maparams] # add zero-lag
sigma2=np.array([1])

acov = arma_acovf(ar=ar, ma=ma, nobs=n_obs, sigma2=sigma2)

Sigma = toeplitz(acov)

corr = correlation_from_covariance(Sigma)

tmp = np.random.rand(n_obs, n_obs)
unrestr_cov = np.dot(tmp,tmp.T)

unrestr_mean = np.random.rand(n_obs, 1)

def show_covariance(mean_vec, cov_mat):
    K = cov_mat.shape[0]
    
    fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(20,8))

    m = ax[0].imshow(mean_vec,
                       cmap='GnBu',
                      )

    K = Sigma.shape[0]

    ax[0].set_xticks([])
    ax[0].set_xticklabels([]);
    ax[0].set_yticks(range(0,K))
    ax[0].set_yticklabels(range(1, K+1));

    #ax[0].set_xlabel('$\mu$', fontsize=24)
    ax[0].set_title('mean', fontsize=24)

    c = ax[1].imshow(cov_mat,
                       cmap="inferno",
                      )
    plt.colorbar(c);


    ax[1].set_xticks(range(0,K))
    ax[1].set_xticklabels(range(1, K+1));
    ax[1].set_yticks(range(0,K))
    ax[1].set_yticklabels(range(1, K+1));  
    ax[1].set_title('Covariance', fontsize=24)

    plt.subplots_adjust(wspace=-0.7)

    #return (fig, ax)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32mC:\Users\eeu227\AppData\Local\Temp/ipykernel_38172/3725173954.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mimport[0m [0mmatplotlib[0m[1;33m.[0m[0mpyplot[0m [1;32mas[0m [0mplt[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;32mfrom[0m [0mstatsmodels[0m[1;33m.[0m[0mtsa[0m[1;33m.[0m[0marima_process[0m [1;32mimport[0m [0marma_acovf[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;32mfrom[0m [0mscipy[0m[1;33m.[0m[0mlinalg[0m [1;32mimport[0m [0mtoeplitz[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

