Traceback (most recent call last):
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\nbclient\client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\eeu227\AppData\Local\Continuum\anaconda3\envs\jbook_env\lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Remember: Python requires you to explictly "import" libraries before their functions are available to use. We will always specify our imports at the beginning of each notebook.
import pandas as pd, numpy as np
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32mC:\Users\eeu227\AppData\Local\Temp/ipykernel_27308/1013790581.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# Remember: Python requires you to explictly "import" libraries before their functions are available to use. We will always specify our imports at the beginning of each notebook.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [1;32mimport[0m [0mpandas[0m [1;32mas[0m [0mpd[0m[1;33m,[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

